### PR TITLE
WAN cumulative patch

### PR DESCRIPTION
**Pull request by obsy**
- if WAN is disabled - allow to merge port wan with lan. It is important for people who want to use full 5-port switch in pure AP mode.
- if dhcp (wired) or static (wired) selected - allow to change default wan interface. This allow to use other wan interface (ethernet via usb), new HiLink modem etc.
- if dhcp (wireless) or static (wireless) selected - allow change mac adress on wifi interface
- new protocol - QMI, to use with new LTE modem like Huawei E398, ZTE MF821D

These functions have been tested by a many people in the last few month is my images.

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I've pulled these updates  into a new branch called wan_qmi, but I have one issue: the addition of the wan_interface control, in particular to the wired modes. To me, this seems like something that should be hidden unless ABSOLUTELY needed, and taken care of automatically based on the user's selections of the other controls, and has the potential to cause some major problems if it is set incorrectly.

Is this control needed for qmi ? Is there a way to detect the qmi interface automatically? (I don't have the hardware right now to test this)

**Comment by obsy** [comment]
Dnia 2015-01-29, o godz. 09:26:49
Eric Bishop <notifications@github.com> napisał(a):

> I've pulled these updates  into a new branch called wan_qmi, but I have one issue: the addition of the wan_interface control, in particular to the wired modes. To me, this seems like something that should be hidden unless ABSOLUTELY needed, and taken care of automatically based on the user's selections of the other controls, and has the potential to cause some major problems if it is set incorrectly.
> 
> Is this control needed for qmi ? Is there a way to detect the qmi interface automatically? (I don't have the hardware right now to test this)

Yes, probably we can detect based on /dev/cdc-wdmX. 
But wan_interface is important in other modes - new Huawei LTE modem in HiLink 
mode is just simple network card via usb. So to use new modem you must select 
dhcp-wired and new nterface (eth2), not router's.
-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by ericpaulbishop** [comment]
There must be a way to automatically determine if an interface is a 3g interface, or at least whether it is provided by USB -- this REALLY needs to be handled automatically. We may be able to start by looking in /sys/kernel/debug/usb/devices, seeing if a 3g modem is attached, and then from there figuring out which interface it is. I'm willing to make the assumption there will be at most one 3g interface connected at a time.

I would work on this... but I need access to the hardware to test what data is available when the hardware is connected, and what the best ways to detect this are.

**Comment by obsy** [comment]
Dnia 2015-01-29, o godz. 09:58:00
Eric Bishop <notifications@github.com> napisał(a):

> There must be a way to automatically determine if an interface is a 3g interface, or at least whether it is provided by USB -- this REALLY needs to be handled automatically. We may be able to start by looking in /sys/kernel/debug/usb/devices, seeing if a 3g modem is attached, and then from there figuring out which interface it is. I'm willing to make the assumption there will be at most one 3g interface connected at a time.
> 
> I would work on this... but I need access to the hardware to test what data is available when the hardware is connected, and what the best ways to detect this are.

In trunk, see line 58-66

https://dev.openwrt.org/browser/trunk/package/network/utils/uqmi/files/lib/netifd/proto/qmi.sh
-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by ericpaulbishop** [comment]
Will /sys/class/usbmisc/[device] exist on Barrier Breaker if a qmi device is plugged as well as trunk?

Is this a solution only for qmi devices (the section you link to only refers to qmi devices), or for 3g modems like the Huawei LTE modem you mention above too? /sys/class/usbmisc doesn't show up when I plug in the one 3g device I do have on Barrier Breaker, but if it's only going to show up for qmi devices or some subset of 3g devices, that's expected. 

Also, will ONLY 3g/lte devices show up in /sys/class/usbmisc? The link shown there requires the device name, so it ends up being circular unless the devices we're interested in are the only things under /sys/class/usbmisc.

Again... I could answer these questions for myself if I had hardware to test, but I'm fumbling in the dark, without some of this basic information.

**Comment by obsy** [comment]
Dnia 2015-01-29, o godz. 10:14:19
Eric Bishop <notifications@github.com> napisał(a):

> Will /sys/class/usbmisc/[device] exist on Barrier Breaker if a qmi device is plugged as well as trunk?
> 
> Is this a solution only for qmi devices (the section you link to only refers to qmi devices), or for 3g modems like the Huawei LTE modem you mention above too? /sys/class/usbmisc doesn't show up when I plug in the one 3g device I do have on Barrier Breaker, but if it's only going to show up for qmi devices or some subset of 3g devices, that's expected. 

No, for hilink config for wan looks like

config interface 'wan'
       option ifname 'eth2'
       option proto 'dhcp'

Where eth2 is interface created by modem driver (cdc-ncm,cdc-ether,cdc-rndis)


> Also, will ONLY 3g/lte devices show up in /sys/class/usbmisc? The link shown there requires the device name, so it ends up being circular unless the devices we're interested in are the only things under /sys/class/usbmisc.

qmi - yes, ncm - yes, hlink and other like cdc-ether,rndis - no.

-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by ericpaulbishop** [comment]
Can you please test/confirm for me that this (shell) code will auto-detect a qmi interface if one exists?

    #!/bin/sh
    qmi_if=""
    if [ -e /sys/class/usbmisc/ ] ; then
    	devnames=$(ls /sys/class/usbmisc)
    	for devname in devnames ; do
    		if [ -e "/sys/class/usbmisc/$devname/device/net" ] && [ -z "$qmi_if" ] ; then
    			qmi_if=$( ls "/sys/class/usbmisc/$devname/device/net" | head -n 1 )
    		fi
    	done
    fi
    echo $qmi_if

**Comment by obsy** [comment]
Dnia 2015-01-30, o godz. 11:13:13
Eric Bishop <notifications@github.com> napisał(a):

> Can you please test/confirm for me that this (shell) code will auto-detect a qmi interface if one exists?


Sorry no. I don't have any qmi device now.

-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by ericpaulbishop** [comment]
In that case, I am not going to merge this branch into master for the foreseeable future. Until this can be implemented without the wan_interface control, and this code can be tested, I'm not going to include these patches.

I will leave this pull request open, though, and if/when this can be updated/tested I will merge it.

**Comment by obsy** [comment]
#!/bin/sh
qmi_if=""
if [ -e /sys/class/usbmisc/ ] ; then
    devnames=$(ls /sys/class/usbmisc)
    for devname in $devnames ; do
        if [ -e "/sys/class/usbmisc/$devname/device/net" ] && [ -z "$qmi_if" ] ; then
            qmi_if=$( ls "/sys/class/usbmisc/$devname/device/net" | head -n 1 )
            break
        fi
    done
fi
echo $qmi_if

root@wdr4300:~# /tmp/qmi.sh
wwan0

For
root@wdr4300:~# ls /sys/class/usbmisc/
cdc-wdm0  lp0
root@wdr4300:~# ls /sys/class/usbmisc/cdc-wdm0/device/net
wwan0

**Comment by ericpaulbishop** [comment]
If the ifname parameter is set to wwan0 is that correct? Or does ifname need to be set to cdc-wdm0 to work? Also, please confirm that this was tested on Barrier Breaker and not trunk.

**Comment by ericpaulbishop** [comment]
If the ifname parameter needs to be set to cdc-wdm0 for qmi to work, please test this revised script:


    #!/bin/sh
    qmi_if=""
    if [ -e /sys/class/usbmisc/ ] ; then
    	devnames=$(ls /sys/class/usbmisc)
    	for devname in devnames ; do
    		if [ -e "/sys/class/usbmisc/$devname/device/net" ] && [ -z "$qmi_if" ] ; then
    			qmi_if="$devname"
    		fi
    	done
    fi
    echo $qmi_if

**Comment by obsy** [comment]
Dnia 2015-02-04, o godz. 12:55:04
Eric Bishop <notifications@github.com> napisał(a):

> If the ifname parameter is set to wwan0 is that correct? Or does ifname need to be set to cdc-wdm0 to work? Also, please confirm that this was tested on Barrier Breaker and not trunk.

wwan0. cdc-wdm0 is control device through which uqmi talking to the modem.

-- 
Pozdrawiam,
 Cezary Jackiewicz

**Pull request closed without merging**
