### PR TITLE
Update menus.txt

### PR DESCRIPTION
**Pull request by RomanHK**
Added two lines

### CODE REVIEW

**Comment by lantis1008** [comment]
Thanks, you’re on the right track now!
Can I please ask you to separate these two lines and place them into their respective plugins? I did this for you with your first lot of changes so you may not have seen this convention.

Init.d is specified here:
package/plugin-gargoyle-initd/files/www/i18n/universal/menu-system_initd.txt
Logread is specified here:
package/plugin-gargoyle-logread/files/www/i18n/universal/menu-system_logread.txt

**Comment by lantis1008** [comment]
See how it is done in DDNS plugin here
https://github.com/ericpaulbishop/gargoyle/blob/88c29c44e6ba6c3093f46001634530a89fdf6353/package/plugin-gargoyle-ddns/files/www/i18n/universal/menu-connection_dyndns.txt

**Comment by RomanHK** [comment]
menu-connection_dyndns.txt is O.K., thanks.

**Comment by lantis1008** [comment]
You have decided to not make the changes?

**Comment by RomanHK** [comment]
So, I do not know who he is communicating with.
I'm sorry, but I'm a complete beginner.
The changes I want to make (the error was probably because I clicked close).

**Comment by lantis1008** [comment]
Let me provide you some very detailed feedback, and then hopefully you can sort it out from there.
The change you want to make is good :+1:, however you have made it in the wrong place :-1:.
The convention is that the menu translations for plugins, belong within the plugin themselves.

To correct the code:
1. Remove the two lines you just added to `package/plugin-gargoyle-i18n-Czech-CS/files/www/i18n/Czech-CS/menus.txt`
```
gargoyle_display_system_initd="Služby"
gargoyle_display_system_logread="Systémové deníky"
```
2. Add the line `gargoyle_display_system_initd="Služby"` to the end of the file `package/plugin-gargoyle-initd/files/www/i18n/universal/menu-system_initd.txt` as a new line
3. Add the line `gargoyle_display_system_logread="Systémové deníky"` to the end of the file `package/plugin-gargoyle-logread/files/www/i18n/universal/menu-system_logread.txt` as a new line
4. Commit this change to the same branch you are already using `czech_i18n_fix`
5. Leave a comment here to let me know you are done and i will check it

**Comment by RomanHK** [comment]
Ah, now I'm going through the repository, and I probably figured it out. You are trying to divide your languages into plugins - each plugin will have your language files.

O.K. give me a few moments, divide and edit them.

**Comment by lantis1008** [comment]
That's right, at least for the menus!

**Comment by RomanHK** [comment]
So I'm finally at home - I'm going to do it.

**Comment by RomanHK** [comment]
So that should be, is it okay?

**Pull request merged**
