### PR TITLE
Rename obfsproxy to obfsproxy-legacy

### PR DESCRIPTION
**Pull request by obsy**
See https://github.com/ericpaulbishop/gargoyle/issues/795

### CODE REVIEW

**Comment by lantis1008** [comment]
Is this going to need updates to all configs as well?

**Comment by obsy** [comment]
Yes, good point.

**Comment by lantis1008** [comment]
We might need to pull the same trick with Openvpn. Looks like on new installs it is pull 2.4.5 from upstream, but we only have 2.4.4, and this ruins the init.d file.

**Comment by obsy** [comment]
openvpn -> gargoyle-openvpn ?

**Comment by lantis1008** [comment]
I think so

**Comment by lantis1008** [comment]
I'm taking care of this now. Just realised i went with "openvpn-gargoyle" instead though. 
Change is difficult due to package variants.

**Comment by obsy** [comment]
Gagroyle uses only openvpn-openssl. So we can rename openvpn to openvpn-gargoyle (or gargoyle-openvpn) and drop variants?
easyrsa also require changing name.

**Comment by lantis1008** [comment]
Could do, but i'd like to leave the possibility open for future, so leaving variants in.
easy rsa seems to be ok because they have version "3", but we have version "2013-xx-xx" which is considered larger "newer" than 3.
But i would like to investigate using 3 anyway so i'll touch on that soon.

**Comment by lantis1008** [comment]
would be great if you could take a quick look at https://github.com/ericpaulbishop/gargoyle/pull/807 before merge.
easy-rsa will be another day, as i don't think it causes an issue (yet).

**Pull request merged**
