### PR TITLE
Fix bug introduced by 1280cd6

### PR DESCRIPTION
**Pull request by lantis1008**

### CODE REVIEW

**Comment by lantis1008** [comment]
Not run tested, but makes sense to me

**Comment by crackself** [comment]
this fix make a new bug: could't update firmware via web upgrade.

**Comment by lantis1008** [comment]
You can do so via the command line. 
I will look at where else this patch touched.

**Comment by crackself** [comment]
could you show that command line,thanks.

**Comment by lantis1008** [comment]
`sysupgrade /path/to/sysupgrade.bin`
Add -n option to not preserve settings. 
Move bin file to /tmp/ first

**Comment by lantis1008** [comment]
Nothing obviously wrong with code. 
Can you please provide errors System logs as you did with the previous issue?

**Comment by crackself** [comment]
ooh,find out the reason,this cause by the old firmware cache.after flash to a stable edition then try the new build firmware,it run fine.

**Comment by lantis1008** [comment]
Great. No worries then.

**Pull request merged**
