### PR TITLE
Fix i18n in channel width

### PR DESCRIPTION
**Pull request by obsy**

### CODE REVIEW

**Comment by obsy** [comment]
```
	Band 2:
		Capabilities: 0x19e3
			RX LDPC
			HT20/HT40
			Static SM Power Save
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 8 usec (0x06)
		HT TX/RX MCS rate indexes supported: 0-23
		VHT Capabilities (0x338001b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			RX antenna pattern consistency
			TX antenna pattern consistency
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: MCS 0-9
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: MCS 0-9
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
		Frequencies:
			* 5180 MHz [36] (20.0 dBm)
			* 5200 MHz [40] (20.0 dBm)
			* 5220 MHz [44] (20.0 dBm)
			* 5240 MHz [48] (20.0 dBm)
			* 5260 MHz [52] (20.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5280 MHz [56] (20.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5300 MHz [60] (20.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5320 MHz [64] (20.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5500 MHz [100] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5520 MHz [104] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5540 MHz [108] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5560 MHz [112] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5580 MHz [116] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5600 MHz [120] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5620 MHz [124] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5640 MHz [128] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5660 MHz [132] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5680 MHz [136] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5700 MHz [140] (27.0 dBm) (radar detection)
			  DFS state: usable (for 3095 sec)
			  DFS CAC time: 60000 ms
			* 5745 MHz [149] (disabled)
			* 5765 MHz [153] (disabled)
			* 5785 MHz [157] (disabled)
			* 5805 MHz [161] (disabled)
			* 5825 MHz [165] (disabled)
	valid interface combinations:
		 * #{ AP } <= 8,
		   total <= 8, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz }
```

Channels with radar detection are normal channel for use. Delete the last line ( radar detect widths: ...), not the other.

**Comment by lantis1008** [comment]
I thought about this, but then wondered.
How can we make sure that the GUI reflects the actual channel in use? The GUI reflects the settings we make, but if DFS kicks us off a channel, that isn't updated in the config so the UI knows nothing about it. 
It's just messy. 

I agree DFS should be used, but the UI needs more thought. 

If Eric is happy to accept this though, I'm going to bump CC to 48153 so that mwlwifi gets DFS support too. 

Also if this is accepted, I'll add to the "allowed channels" arrays.

**Comment by obsy** [comment]
We don't know, LuCi also.  Probably we should add info about used channel on overview page + warning about DFS.

**Comment by lantis1008** [comment]
made the changes to the JS for the allowed channels. Just testing something else first before i make a commit. Fresh build underway.

**Pull request merged**
