### PR TITLE
Allow bandwidth graph colours to be set by theme

### PR DESCRIPTION
**Pull request by lantis1008**
Pulls the "color" attribute of the label for each plot and applies it to the polyline object color and fill attributes

### CODE REVIEW

**Comment by d3fz** [comment]
Nice. 👍 

Can you provide any screenshots showing how it looks? 

For some reason, it's not working on my end. When setting a different color, only the labels color change. This should also affect graphs color, right?

Clearing browser cache doesn't seem to fix it.

**Comment by lantis1008** [comment]
bccb7114-7803-413c-80f4-e29ee324d943

You took the changes from svg_bandwidth.js as well?
This is a quick change with softer colours

**Comment by d3fz** [comment]
>This is a quick change with softer colours

Those graphs colors look smooth on a dark background. Nice.

>You took the changes from svg_bandwidth.js as well?

Yes. 

After further testing, console was throwing `TypeError: window.parent.getElementById is not a function`

Changing to `window.parent.document.getElementById` fixed the issue.

___

Oddly enough, `bandwidth_expand.sh` header has some duplicate code:

```Javascript
gargoyle_header_footer -m -c "internal.css" -j gargoyle_header_footer -m -c "internal.css"
````

**Comment by lantis1008** [comment]
Thanks I’ll double check that error. I wasn’t seeing it. 
What browser?

**Comment by d3fz** [comment]
Vivaldi (Chromium based).

Also tested with latest Chrome/Opera/Edge and Firefox Quantum. Same problem.

**Comment by lantis1008** [comment]
Thanks for pointing it out. Was a typo in the commit, was fine on my router (hence why i saw no bugs). Whoops.

**Comment by ericpaulbishop** [comment]
Looks great, merged.

**Comment by lantis1008** [comment]
Whoops. Accidentally pushed the theme as well. 
I’ll do a commit to enable it for building later this week.

**Comment by d3fz** [comment]
I was about to make a comment on that, nice work on the horizontal menu bar by the way. Maybe now it should be possible/easier to address those two remaining themes in #654?

**Comment by lantis1008** [comment]
Definitely. They are next on my todo list :)

**Pull request merged**
