### PR TITLE
Update button CSS class names in various pages

### PR DESCRIPTION
**Pull request by d3fz**
## Changelog
- Update button CSS class name on some pages for consistency with other pages
  - This also adds more custom CSS classes to some JS button elements
- Add a confirmation dialog box for the following button operations:
   - "Clear History" on Web Monitor page (`webmon.sh`) 
   - "Uninstall" package/plugin on Plugins page (`plugins.sh`)
   - "Reboot" router on Reboot/Schedule page (`reboot.sh`)
- Minor update to PT-BR language pack

### CODE REVIEW

**Comment by d3fz** [comment]
>Are you able to provide any more preview screenshots for your theme?

Sure. Is there any specific page you'd like to see for comparison?

>I’m working on fixing Gargoyle Modern and want to make sure we aren’t going down the same path.

How's the progress on Gargoyle Modern theme so far?

**Comment by lantis1008** [comment]
Maybe just overview + Connection basic?

Also I’m going to make a change to the code to allow the theme to dictate colours of graphs on bandwidth usage page. This may be of use to you. 

Gargoyle Modern is going ok. I’m implementing a horizontal menu bar and I’m strugglng to get it working neatly.

**Comment by lantis1008** [comment]
It looks great. Well done.
I think this would be a good candidate to replace "Gargoyle-Modern". Please feel free to overwrite that theme with this one. Unless you already have a name picked out that you are attached to, in which case continue as you were.

**Comment by obsy** [comment]
It really looks good.

**Pull request merged**
