### PR TITLE
Adjust clean_ipkg_partial patch and fix arping+sha1sum

### PR DESCRIPTION
**Pull request by lantis1008**

### CODE REVIEW

**Comment by lantis1008** [comment]
Thanks will do. Disappointed, I already kicked off a full build last night for testing lol.

**Comment by lantis1008** [comment]
@d3fz
Can you please provide the opposite translation for basicS.BrNote i.e. inside the AP subnet? I’ll include it in my next commit.

**Comment by d3fz** [comment]
>Can you please provide the opposite translation for basicS.BrNote i.e. inside the AP subnet? I’ll include it in my next commit.
I've currently set "setar dentro da sub-rede do AP", but happy to change it if this is not accurate.

It's perfectly accurate. 

Thank you for your work.

**Comment by lantis1008** [comment]
Lucky guess!

**Pull request merged**
