### PR TITLE
Bootstrap integration - phase 1

### PR DESCRIPTION
**Pull request by stopspazzing**
I have successfully integrated bootstrap for a responsive design & layout. More information on the specifics are located [here](https://www.gargoyle-router.com/phpbb/viewtopic.php?f=13&t=7599&p=37203#p37203) and well as my custom bootstrap build, and some images of the new design.

Caveats:

- This phase 1 (personally my 4th complete code rework) is just for showing off possibilities and I am looking for as much feedback as possible. Also need people with screen readers to test to make sure everything works, any problems can be easily fixed.
- Device name in [sidebar header](https://github.com/stopspazzing/gargoyle/blob/master/package/gargoyle/src/gargoyle_header_footer.c#L506) under logo isn't working, tried pretty darn hard to get it working. Must be something I'm missing.
- Some of the very LONG pages like basic.sh, need some more tweaks and code cleanup which is no longer needed. Still would like wifi section on basic.sh to be broken into 3 parts.
- Any features used were kept to IE8+ FF3+ All chrome/opera/safari versions for compatibility. Any hidden text will still be read on screen readers. Kept this to only the login screen currently.
- Only javascript added was getting the sidebar to open when clicked on mobile, located at the bottom of the [gargoyle header footer](https://github.com/stopspazzing/gargoyle/blob/master/package/gargoyle/src/gargoyle_header_footer.c#L673) file.
- You CAN flash over this build without having issues on 1.9.x builds. I backed up my settings as a precaution, as I suggest you do the same.
- All *.sh/.css files can be modified on the fly on a running router without issues, so if you want to test changes or tweaks, modify away. Most of the *.js can be except common.js, which likes resetting your settings when modified.
- I'm hoping to get this merged before or with 2.0.x builds. Sooner the input the sooner the changes can be applied.
- [theme.css](https://github.com/stopspazzing/gargoyle/blob/master/package/gargoyle/files/www/themes/Gargoyle/theme.css) is the primary .css file; any changes to it will override everything else. Thinking themes should have a default 'theme.css' file, possibly even a 'theme.js' since some people need to add custom js.
- Yes, technically the sidebar menu is on the right side, and the content is on the left, why? because moving the code around caused it not to display the content on pages. Bootstrap lets you 'switch' columns which is what I am doing to get everything working. A better fix would be to put the sidebar menu before the actual content, but I couldn't get this working.
- Some pages generate content via their .js equivalent file, however, I have yet to modify any ,js files outside the table.js file, so some tables and content looks off. These changes are planned, but currently waiting for feedback before I continue.
- I have some idea's of making the menu look better since I currently think it looks bland.
- There are still comments in the code which I used to debug the sidebar menu, currently just pointers and only can be seen in [source](https://github.com/stopspazzing/gargoyle/blob/master/package/gargoyle/src/gargoyle_header_footer.c#L388)
- Technically you dont need anything other than the [gargoyle](https://github.com/stopspazzing/gargoyle/tree/master/package/gargoyle) package, so if you want to use this on a newer build of gargoyle, just copy folder over. Worse case, only the frontend (aka web interface) won't work, and a simple sysupgrade via terminal to flash to a working build fixes the issue.

### CODE REVIEW

**Comment by stopspazzing** [comment]
As a side note:I was also thinking of making the header/footer file pull html from template files IN the theme folder, so different themes can load/modify content. Making it modular and completely customizable. Just an idea.

**Comment by lantis1008** [comment]
I wish I wasn't busy at the moment otherwise I'd build this right now.

**Comment by ericpaulbishop** [comment]
First, I notice you have travis-ci stuff in there. If you have that working, it would be great if you commit that in a separate pull request, because I would merge that right away.

Second... this doesn't look like it's going to be backwards compatible with existing themes, of which there are many, which concerns me. You over-wrote the page layout for pretty much every page rather than altering CSS that works with the existing layout (or CSS that works with a modified layout and using javascript to modify it dynamically, which would also be perfectly fine and backwards compatible). I won't say no definitively, I might be persuaded, but when you're invalidating every theme that anyone has developed thus far... you need a very compelling reason to switch. What advantages do you feel are worth that in this implementation?

Also, how much space is this going to add (or subtract? maybe you've refactored it so the CSS is way more efficient? That would fall under "compelling reasons" above ;-) ) I'm about to drop support for 4M routers, but space is still at a premium. 

Regardless of everything else, I do very much like the idea of allowing template files in the theme folder to make things more dynamic.

Finally -- while I don't care what logo you have in your own theme, the Gargoyle logo itself isn't going to change. I would consider changing the color, but the logo itself will always be the same, and will appear in the default theme, whatever it is, no matter what.

**Comment by stopspazzing** [comment]
I will answer all the questions in the order you asked them.

1. Travis-ci isnt 100% working and i'll remove it from the pull request. Wasn't my main priority, and was trying to get it working.
2. I worked on this for 5-6 months, of which 2 months were dedicated to attempting to integrate bootstrap without issue into the current theme. I tried, however, because of the way bootstrap is designed, it would need more work arounds than was worth the time to do. There are 2 major pro's to the bootstrap design, 1. Being as its the most widely used responsive design out there, anyone who can develop a simple theme for your custom original theme, would have the easiest time to modify for this. Literally all the important css is in the theme.css, and overrides anything else. 2. Regardless of the fact that it is responsive, since I stuck to the default Bootstrap class's, ANYONE can easily generate a new theme file using: [customizer](https://getbootstrap.com/customize/?id=6ddf9eba192f36caabda#less-variables) ; I named mine theme.css but it spits them out as bootstrap.theme.css. Meaning even someone who doesn't know css design can goto that page change a few settings, download the new theme and rename the file and paste it into the Gargoyle theme folder and have a completely different color layout & design without needing to have any experience in html and css.
3. The size of the /www currently on the router is 1071KB. The size of Gargoyle theme folder is 97.5KB on the router. I believe this is around the same size was before or smaller, cant remember off the top of my head, maybe someone can `du -h /www` via ssh and let me know. This is with the optimized files + minified bootstrap.css. Some layout files can be modified further to shrink their size, removing unneeded code, specifically the large files (basic.sh comes to mind). From the internal.css and common.css files, I combined many of the same used code so that also saved space.
4. I was trying to play around with templating the header/footer file but didnt have the time to fully test it, would allow people like me to move the nav from sidebar to top for instance, with simple layout tweaks without having to recompile the whole firmware. Currently, no other Router firmware is module like this... Would also allow people with the space to install larger themes that contain newer and more complicated js/css files [like using morris.js](https://morrisjs.github.io/morris.js/). My main idea would be to make a new theme which supports only IE11+ latest browsers and move away from using js functions to html5, like removing cookies and input checks, html5 combines both to make it easier and faster since things can be cached and threaded to be crunching info in the background. But that's for another time.
5. Was a suggestion, will remove it and put up a cleaned version of the currently used one. No worries. And thanks for letting me know.

Another idea would be to move the internal.css and common.css to a /css folder within the theme folder since those are needed files keeping the Gargoyle theme folder clean, and adding a /js folder also, again allowing people to add js files, which the theme checks and auto loads if any found. Hmm reminds me of wordpress, maybe a config file within the theme that allows overrides to locations of files or compatibility information or something. I have too many ideas.

**Comment by jaf0** [comment]
root@gargoyle:~# du -h /www
3.5K	/www/data
5.0K	/www/hooks/login
5.0K	/www/hooks
75.5K	/www/i18n/English-EN
13.0K	/www/i18n/graphics
3.5K	/www/i18n/universal
512	/www/i18n/Polish-PL
92.5K	/www/i18n
470.0K	/www/js
38.0K	/www/templates
52.0K	/www/themes/Gargoyle/images
82.5K	/www/themes/Gargoyle
512	/www/themes/Dark One/images
1.5K	/www/themes/Dark One
512	/www/themes/Light Theme/images
2.0K	/www/themes/Light Theme
512	/www/themes/Theme by matei/images
2.0K	/www/themes/Theme by matei
88.0K	/www/themes
25.5K	/www/utility
969.5K	/www

**Comment by stopspazzing** [comment]
Updated files to requested changes.

Difference in size is ~110KB; I probably can squeeze more out of it.

**Comment by stopspazzing** [comment]
After some tweaks and modifications:
```
root@Gargoyle:~# du -h /www
3.5K	/www/data
2.5K	/www/hooks/login
2.5K	/www/hooks
78.5K	/www/i18n/English-EN
13.0K	/www/i18n/graphics
2.0K	/www/i18n/universal
93.5K	/www/i18n
446.5K	/www/js
38.0K	/www/templates
9.0K	/www/themes/Gargoyle/images
94.0K	/www/themes/Gargoyle
94.0K	/www/themes
25.5K	/www/utility
945.0K	/www
```

So now it's actually smaller. :smiley: 

The tools I used can actually be used on other packages also. I used nodejs(latest v5.x) + uglifyjs2 + uglifycss + https://compressor.io/.

Need to modify the build script to include new steps and update the old stuff. Currently, there is code in the (re)build for compressing the javascript with the no longer updated uglifyjs. Need to upgrade to uglifyjs2. There is no script to compress/minify the .css oddly enough. I manually uploaded the images to compressor.io and replaced them with the compressed versions. Going to move the wait_msg_background to css which will save space also.

The only difference in switches in uglifyjs2 is the input file is before the switches, not after like it is currently and the folder name is uglify2.

Still looking for a way to minify .sh files, not sure if this would work: https://stackoverflow.com/questions/9907200/how-to-minify-obfuscate-a-bash-script

**Comment by ericpaulbishop** [comment]
Sorry it's taken a while for me to reply... but if this is actually smaller, I think you've convinced me that this approach is good. I admit, I haven't built from this branch yet to see what your layout looks like (maybe post some screenshots?), so I can't comment on the specifics but updating the layout to use modern CSS tools (bootstrap) does make sense given that it's not adding space.

That said, this is a large pull request and merging it will not happen right away, as this is changing something fairly fundamental. I'm going to focus on getting the known-devices pull request in shape to merge first (this is long overdue), but I think this has a great deal of potential.

**Comment by stopspazzing** [comment]
Awesome. That's wonderful news.
There are some images on the forums, but let me add new ones of what I currently have it. Just a reminder, haven't modified any .js files outside table.js, and some pages need small tweaks to make things uniform (h1's for instance and colors of buttons on some pages):

https://i.imgur.com/wVotl6P.png
https://i.imgur.com/30l3zuf.png
https://i.imgur.com/jflo90y.png
https://i.imgur.com/60ri64a.png
https://i.imgur.com/KPyH4I5.png
https://i.imgur.com/Ye5TYiq.png
https://i.imgur.com/p1Jph0R.png
https://i.imgur.com/PT5UCma.png
https://i.imgur.com/GYk1keB.png
https://i.imgur.com/pOWwDJp.png
https://i.imgur.com/rSNStDx.png
https://i.imgur.com/9BQ7lto.png
https://i.imgur.com/pgPQvhN.png
https://i.imgur.com/o1ahQqm.png
https://i.imgur.com/O0UZQIC.png
https://i.imgur.com/z87LzUm.png
https://i.imgur.com/GiIKUmi.png
https://i.imgur.com/fwFsFD2.png
https://i.imgur.com/8tcia5Q.png
https://i.imgur.com/TH814Ha.png
https://i.imgur.com/o89NPwe.png
https://i.imgur.com/yldpMM9.png
https://i.imgur.com/6aqDNvA.png
https://i.imgur.com/7dhJJtP.png
https://i.imgur.com/dBgvh2M.png

**Comment by lantis1008** [comment]
What is required to get this finished? And if i begin testing it on a working router, what do i need to watch out for at the moment?

**Comment by nworbnhoj** [comment]
Let's keep a common code formatting throughout Gargoyle - right or wrong it needs to be consistent across the code-base.

**Comment by stopspazzing** [comment]
@lantis1008 
Yeah, as mentioned ignore the *.js files, I am using Atom.io for editing the code. This works out of the box, recent pull in march so has wrt1900ac tweaks. 

You can override any files expect the [header/footer file](https://github.com/stopspazzing/gargoyle/blob/master/package/gargoyle/src/gargoyle_header_footer.c), anything in the [gargoyle theme folder](https://github.com/stopspazzing/gargoyle/tree/master/package/gargoyle/files/www/themes/Gargoyle), or any *.sh files and will work as advertised. You only need the [gargoyle package folder](https://github.com/stopspazzing/gargoyle/tree/master/package/gargoyle). So do a recent pull, then replace the gargoyle folder with one in pull.

@nworbnhoj 
I have a plugin called "beautify" which I have also noticed needs to be configured as I agree with you 

I will overwrite all *.js files with defaults since they aren't a priority currently. Still will work without it, just wont be as pretty with buttons or tables :cry: . I will add them to my to-do for phase 2.

**Comment by stopspazzing** [comment]
After some discussion, to clean this up and make it easier to integrate, going to close this PR and use it as a reference only, then create a clean fork, add my changes and stash them, then use that PR to continue work.

**Pull request closed without merging**
