### PR TITLE
Visual unification of interface, I18n compatability error correction in e-mail plugin, DHCP alternative default gateway option & change lease time units from hours to minutes

### PR DESCRIPTION
**Pull request by WildRat**
Small visual change

### CODE REVIEW

**Comment by WildRat** [comment]
Here: it's in their official FAQ section: [https://www.quad9.net/#/faq#my-system-has-a-spot-for-a-"secondary"-dns-server-is-there-a-"secondary"-address-i-should-use](url)

**Comment by lantis1008** [comment]
Ok fair enough. Apologies had not spotted that. 

It does say only if it is required, but we can put it in.

**Comment by WildRat** [comment]
Done

**Comment by ispyisail** [comment]
Gateway option is good, not used often but a nice option

**Comment by WildRat** [comment]
I'm thinking, maybe, to add option to include "DNS servers IP" to DHCP answer?

**Comment by ispyisail** [comment]
"I'm thinking, maybe, to add option to include "DNS servers IP" to DHCP answer?"

It would be good if you could set "DNS server" per IP Address or range of IP address?

**Comment by ispyisail** [comment]
Also if you in the zone, DHCP relay would be a nice option?

**Comment by lantis1008** [comment]
I think go do invidividual DNS you would need to move away from the split /etc/hosts and /etc/ethers method and into the config dhcp file. 
I believe one of the open pull requests about user groups already did this so it could be copied. 

It’s a pretty significant change though

**Comment by ispyisail** [comment]
Speaking of "Gateways" It would be really good if we could also set the Gateways per "IP" or "IP Range" or per "group"

I've been in a remote location with poor cell phone coverage. Family members kept loading up my 4G. It would be good to be able split the up into different gateways (more 4G internet sources) ?

**Comment by lantis1008** [comment]
That’s what MWAN3 does and it’s not going to play nice with Gargoyle

**Comment by ispyisail** [comment]
@WildRat have you finished and tested?

**Comment by WildRat** [comment]
Yes, i tested. I use GitHub for Windows and it puts all in one Pull.

**Comment by d3fz** [comment]
+1 for splitting into multiple/smaller pull requests. 👍 

Easier to read/review the code changes quickly and better chances of getting merged sooner.

**Comment by d3fz** [comment]
You can't do this through GitHub website or GitHub app. 

**You have to do this locally and through the Git Terminal**, then push your changes online and open a new pull request when you're done.

**I can't help you through the whole process**, but [this should give you an idea and get you started](https://glebbahmutov.com/blog/splitting-pull-request/).

Google is your friend on this one.

**Comment by ericpaulbishop** [comment]
Yes,  please split this up so that each feature is its own pull request. There's a lot going on here and I'd like to see each one by itself.

**Comment by WildRat** [comment]
Ok. Then I just close this one and try to make couple new one's one by one.

**Comment by ericpaulbishop** [comment]
Thank you. I appreciate you taking the time to separate them, so I can review and approve them individually.

**Pull request closed without merging**
