### PR TITLE
Patch in hook_chains/tables for 4.14

### PR DESCRIPTION
**Pull request by lantis1008**
I'm still getting boot loops, haven't tested if this solves it yet.
Also getting complaints that curl does not have https support built in. I may have made a bad config adjustment there in my last commit

### CODE REVIEW

**Comment by lantis1008** [comment]
Yes think I forgot to include at least one ssl library. I think ewget may be suffering from this also

**Comment by lantis1008** [comment]
Fixed libcurl issue. added ARPing utility which got left out

**Comment by lantis1008** [comment]
Clean build was better. Got a kernel oops that didn't halt the system when loading IMQ for the first time. Subsequent loads seemed ok.
```
Wed Apr 25 21:44:53 2018 daemon.err insmod: module is already loaded - sch_prio
Wed Apr 25 21:44:53 2018 daemon.err insmod: module is already loaded - sch_tbf
Wed Apr 25 21:44:53 2018 daemon.err insmod: module is already loaded - cls_fw
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  469.792058] ------------[ cut here ]------------
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  469.796705] WARNING: CPU: 1 PID: 14707 at net/netfilter/core.c:319 __nf_unregister_net_hook+0xa0/0xa8
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  469.805975] hook not found, pf 2 num 0
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  469.805976] Modules linked in: qcserial pppoe ppp_async option cdc_mbim uvcvideo usb_wwan sierra_net sierra rndis_host qmi_wwan pptp pppox ppp_mppe ppp_generic nf_nat_pptp nf_conntrack_pptp nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE huawei_cdc_ncm gspca_zc3xx gspca_ov534 gspca_main ebtable_nat ebtable_filter ebtable_broute cdc_ncm cdc_ether xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_iprange xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connlabel xt_connbytes xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CLASSIFY videobuf2_v4l2 usbserial usbnet usblp ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  469.880711]  ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_fsm ts_bm slhc nft_set_rbtree nft_set_hash nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir_ipv4 nft_redir nft_quota nft_numgen nft_nat nft_meta nft_masq_ipv4 nft_masq nft_log nft_limit nft_exthdr nft_ct nft_counter nft_chain_route_ipv6 nft_chain_route_ipv4 nft_chain_nat_ipv4 nf_tables_ipv6 nf_tables_ipv4 nf_tables_inet nf_tables nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_redirect nf_nat_proto_gre nf_nat_masquerade_ipv4 nf_nat_irc nf_conntrack_ipv4 nf_nat_ipv4 nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_proto_gre nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  469.952494]  nf_conntrack_ftp nf_conntrack_broadcast ts_kmp nf_conntrack_amanda nf_conntrack iptable_mangle iptable_filter ipt_ECN ip_tables input_core ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 crc_ccitt cdc_wdm cdc_acm br_netfilter fuse em_cmp sch_teql em_nbyte cls_basic sch_dsmark sch_pie sch_codel sch_gred em_meta act_ipt sch_multiq sch_prio act_police em_text sch_sfq sch_fq sch_red act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress videobuf2_vmalloc videobuf2_memops videobuf2_core v4l2_common videodev mwlwifi mac80211 cfg80211 compat xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  470.023591]  ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink xt_IMQ imq(-) ipt_weburl ipt_webmon ipt_timerange ipt_bandwidth ip6t_rt ip6t_frag ip6t_hbh ip6t_eui64 ip6t_mh ip6t_ah ip6t_ipv6header ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables nfsd nfs msdos ip_gre gre ip_tunnel tun vfat fat lockd sunrpc grace hfsplus nls_utf8 nls_koi8_r nls_iso8859_2 nls_iso8859_15 nls_iso8859_13 nls_iso8859_1 nls_cp866 nls_cp852 nls_cp850 nls_cp775 nls_cp437 nls_cp1251 nls_cp1250 dma_shared_buffer ecb ohci_platform ohci_hcd gpio_button_hotplug mii
Wed Apr 25 21:44:53 2018 kern.warn kernel: [  470.089881] CPU: 1 PID: 14707 Comm: rmmod Not tainted 4.14.27 #0
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.095912] Hardware name: Marvell Armada 380/385 (Device Tree)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.101870] [<c010f600>] (unwind_backtrace) from [<c010b308>] (show_stack+0x10/0x14)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.109651] [<c010b308>] (show_stack) from [<c05f6688>] (dump_stack+0x88/0x9c)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.116906] [<c05f6688>] (dump_stack) from [<c0121e40>] (__warn+0xe4/0x100)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.123899] [<c0121e40>] (__warn) from [<c0121e94>] (warn_slowpath_fmt+0x38/0x48)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.131415] [<c0121e94>] (warn_slowpath_fmt) from [<c053ff0c>] (__nf_unregister_net_hook+0xa0/0xa8)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.140502] [<c053ff0c>] (__nf_unregister_net_hook) from [<c0540240>] (nf_unregister_net_hooks+0x208/0x214)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.150288] [<c0540240>] (nf_unregister_net_hooks) from [<c04feb30>] (ops_exit_list+0x38/0x60)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.158939] [<c04feb30>] (ops_exit_list) from [<c04fee2c>] (unregister_pernet_operations+0x64/0xb0)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.168025] [<c04fee2c>] (unregister_pernet_operations) from [<c04fee94>] (unregister_pernet_subsys+0x1c/0x2c)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.178098] [<c04fee94>] (unregister_pernet_subsys) from [<bf23d018>] (cleanup_module+0x48/0x1030 [imq])
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.187659] [<bf23d018>] (cleanup_module [imq]) from [<c0185844>] (SyS_delete_module+0x148/0x1d4)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.196572] [<c0185844>] (SyS_delete_module) from [<c0107980>] (ret_fast_syscall+0x0/0x54)
Wed Apr 25 21:44:54 2018 kern.warn kernel: [  470.204879] ---[ end trace 89f690be4e9bed78 ]---
Wed Apr 25 21:44:54 2018 kern.info kernel: [  470.322100] IMQ driver unloaded successfully.
Wed Apr 25 21:44:54 2018 kern.info kernel: [  470.392196] 	Hooked IMQ after mangle on INPUT
Wed Apr 25 21:44:54 2018 kern.info kernel: [  470.452147] 	Hooked IMQ after mangle on FORWARD
Wed Apr 25 21:44:54 2018 kern.info kernel: [  470.456720] IMQ driver loaded successfully. (numdevs = 1, numqueues = 1, imq_dev_accurate_stats = 1)
Wed Apr 25 21:44:54 2018 kern.info kernel: [  470.465907] 	Hooking IMQ before NAT on PREROUTING.
Wed Apr 25 21:44:54 2018 kern.info kernel: [  470.470721] 	Hooking IMQ after NAT on POSTROUTING.
```

**Comment by lantis1008** [comment]
Ping @ericpaulbishop
Also 18.06 branched

**Comment by lantis1008** [comment]
I believe there is a problem with ewget. ddns_gargoyle doesn't seem to be able to pull anything with HTTPS. I've tried to correct this myself with no luck. First thought was the mismatch in
https://github.com/ericpaulbishop/gargoyle/blob/base_on_openwrt_remerge/package/ewget/Makefile#L53
vs
https://github.com/ericpaulbishop/gargoyle/blob/base_on_openwrt_remerge/package/ewget/src/Makefile#L8

**Comment by ericpaulbishop** [comment]
Thanks for pointing this out, I'm taking a look now

**Pull request merged**
