### PR TITLE
Fix checkbox/label elements arrangement on various pages

### PR DESCRIPTION
**Pull request by d3fz**
## Changelog
- Remove the gap between these elements for better readability/scan and improved user interaction
- Rearrange checkbox/label order on some pages for consistency throughout the system
- Fix checkbox/label vertical alignment and label word wrap on mobile view (see last screenshot below)
- Minor HTML formatting fixes

## Screenshots
| Before  | After |
| ------------- | ------------- |
|b8a2d31c-2ab7-4481-961a-810b6e2d0fd5				|3544459d-31c3-45c2-99c6-315e75a9302b				|
|f5671e8f-c310-4d17-a6c9-f760f6b5c5b4				|9d5de2b7-a580-44e2-8253-e540db1a7117 				|
|0caecbcb-6ed4-45ba-82ac-81363305b0f4				|3ff99487-d9c7-4944-84f4-0f36996cc0ee				|
|16de6ea4-5ece-4bc1-9e0a-34f8e87b61b0				|b1e67c63-5aa2-4f74-989b-07c10d127eb9				|

### CODE REVIEW

**Comment by d3fz** [comment]
The last screenshot shows the behavior on a 360px screen, I think. 

I've just tested on a 200px screen (is there any smartphone that small?)

d0427611-7937-4200-a789-388907dfe03b

a133670e-aabb-4360-8ce3-dc3f43aff3aa

**Comment by lantis1008** [comment]
Yep that looks good. 
No there isn’t but I always squish the window to unreasonable size when testing just to be sure. 

I know *one day* someone will complain that they use Gargoyle in a 50x50px window in the corner of their screen and it doesn’t look right. Lol

**Comment by d3fz** [comment]
I definitely see your point. I tend to test it like this too.  

Yes, that is very likely to happen. Or maybe they're accessing the GUI through a smartwatch screen, because why not, right? Good luck with that. lol

**Comment by d3fz** [comment]
Forgot to update the OpenVPN page. Also updated the OpenVPN template for consistency with similar forms (i.e. LAN section on basic.sh)
### Screenshots
a2bb25ee-ceb8-4a6f-b2bd-cad19d3d49ce
e9a95a78-d388-4667-bbbc-a495ed576ba8
23ac05e1-5737-47d6-9159-e8bb2201cd84

**Pull request merged**
