### PR TITLE
plugin-gargoyle-ping-watchdog: Add IPv6 support

### PR DESCRIPTION
**Pull request by lantis1008**
Please review @obsy as it is your plugin originally 😄

### CODE REVIEW

**Comment by obsy** [comment]
Looks good, but... Should be wan6 raised, if  wan6 is disabled in config?

**Comment by obsy** [comment]
Disabled by setting ipv6=0 in wan secition. I don't use ipv6, I can't test this.

**Comment by lantis1008** [comment]
I tested this, and `ifup wan6` did nothing on a device where network.wan.ipv6=0 (besides a bit of log spam).
I think for now this is ok?

**Comment by obsy** [comment]
LGTM

**Pull request merged**
