### PR TITLE
Gui overhaul latest

### PR DESCRIPTION
**Pull request by lantis1008**
Restore i18n to new GUI. 
Update Portuguese language pack. 
Update all languages to suit new GUI. 

Besides getting the other themes converted, and dealing with horizontal vs vertical layouts, we are now getting very close. Could you please provide any additional commentary?

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I will get back to you sometime tomorrow, very likely late in the evening.

Sorry I've been a bit out to lunch lately, things have been absolutely crazy. My wife and I just bought a home, and everything involves with that was eating up a bunch of my available time. Things should return to normal shortly.

**Comment by lantis1008** [comment]
Not a problem. 
I was actually going to suggest commit access on the basis of trivial commits (kernel updates, bug fixes etc). Large paradigm shifting commits still being run by you (this, my layer 7 replacement etc). 

Congratulations on the home. That is great news.

**Comment by ericpaulbishop** [comment]
I see two remaining issues which are related, but they're kind of big: Splitting Controls to two lines, and font size. The motivation for addressing both is the same: the new gui seems to take up significantly more space than the old gui, even splitting things out into columns. On mobile it seems quite good, but now on desktops it seems rather clunky.

Right now, I have to scroll twice as far as before just to scroll down through all the controls in the Connection/Basic wireless section. Before they all fit on one screen. I think part of the issue in making things fit is that the new font size for the labels and controls is larger than it was before, which I don't think is a good idea.

I'd really like to go back to trying to having labels on the left and controls on the right instead of splitting between rows like the new gui is currently doing, at least for how everything is displayed to desktop users. Ideally, on horizontally constrained screens this would wrap, while on larger screens it would remain on the same line. On the status screen the labels and values are on the same line, and this seems like what I think would be best elsewhere as well.

Tonight and tomorrow I'm going to work on updating the formatting and font size of the labels/controls, focusing first on the Connection/Basic section.

**Comment by lantis1008** [comment]
Agreed, Connection->Basic is probably the page with the most work needed and the least attention paid to it.
If you come up with a set of changes that you need applied globally, let me know and i can work through them.

**Comment by ericpaulbishop** [comment]
Please take a look at the formatting changes I'm making to the Connection/Basic page. The grid system in bootstrap can be nested, and I'm using a secondary grid to implement a two-column layout similar to how things were before within the panels.

If you could take what I've done (for now just in the WAN and LAN sections of the Connection/Basic section, I'm working on Wireless now), and start applying it to other sections, that would be a huge help.

**Comment by lantis1008** [comment]
Will do.

**Comment by lantis1008** [comment]
Just applied your changes to connection->basic. it looks significantly better. i appreciate your input as always.
Applying these changes globally will take about a week at a guess. Will let you know and then open up a fresh PR.

**Comment by ericpaulbishop** [comment]
Looking at the graph it looks like you merged master, but not my gui_overhaul branch -- make sure you're merging the right one. Also, please note I'm not done updating Connection/Basic. I Still need to finish up the wireless and bridge sections.

**Comment by lantis1008** [comment]
Yea I made a pretty big balls up of the whole thing last night trying to do multiple things at once. 

I did intend to bring in master also to keep on top of any merge conflicts (e.g. Obsy changes) as well.

**Comment by lantis1008** [comment]
If you take a look, I actually have your changes brought in, but it still thinks I've not merged the PR.

**Comment by ericpaulbishop** [comment]
My mistake, you're right, it just wasn't showing up in the graph. Thanks for doing the merge with master, that helps.

**Comment by lantis1008** [comment]
I had to do some wrangling to get my repo back into a workable state. I apologise for any future complications this may cause. I'll resolve them as they become apparent.

**Comment by ericpaulbishop** [comment]
Don't worry about it. Everything looks fine, and you saved me the trouble of having to merge in the master branch myself.

**Pull request merged**
