### PR TITLE
Check for sufficient space on new plugin root drive

### PR DESCRIPTION
**Pull request by nworbnhoj**
When a user attempts to change the plugin root to a location with
insufficient space the user is alerted and a resolution suggested.

resolves; ericpaylbishop/gargoyle#426

### CODE REVIEW

**Comment by nworbnhoj** [comment]
Hold fire - bug found (I think)

**Comment by obsy** [comment]
Uncaught TypeError: Cannot read property 'Bytes-Free' of undefined   line 116.

Some info:
var pkg_dests = [];
pkg_dests['ram'] = [];
pkg_dests['ram']['Root'] = '/tmp';
pkg_dests['ram']['Bytes-Free']  = 13897728
pkg_dests['ram']['Bytes-Total'] = 14606336
pkg_dests['plugin_root'] = [];
pkg_dests['plugin_root']['Root'] = '/plugin_root';
pkg_dests['plugin_root']['Bytes-Free']  = 532480
pkg_dests['plugin_root']['Bytes-Total'] = 917504
pkg_dests['root'] = [];
pkg_dests['root']['Root'] = '/';
pkg_dests['root']['Bytes-Free']  = 532480
pkg_dests['root']['Bytes-Total'] = 917504
pkg_info = [];
.....
var storageDrives = [];
storageDrives.push(["/dev/sda1","/tmp/usb_mount/000e863a-01","/tmp/usb_mount/dev_sda1","Ext4", "985358336", "967065600"]);
var pluginRootSize=1057000;

Error after changing plugin root to /dev/sda1 (pendrivie)

**Comment by nworbnhoj** [comment]
Yep - that would be the bug that I mentioned above.
I will fix it later today when I am near a router again

**Comment by nworbnhoj** [comment]
OK - that bug is now fixed in [#429](https://github.com/ericpaulbishop/gargoyle/pull/429)

**Pull request merged**
