### PR TITLE
Use faster table methods

### PR DESCRIPTION
**Pull request by stopspazzing**
Faster and easier to use .createTHead() and row.insertCell() than to create a element and append to it. When deleting rows, use deleteRow(). See http://www.w3schools.com/jsref/dom_obj_table.asp for more improvements.

Don't merge quite yet, there is some more code I can edit to speed things up. Will be doing revisions.

### CODE REVIEW

**Comment by d3fz** [comment]
Any news about this ?

Would these changes cause any problems if i test it on my own router ?

**Comment by ispyisail** [comment]
@stopspazzing whats the status of this patch?

**Comment by lantis1008** [comment]
I think this one should maybe just close. I don’t know that there are any performance gains to be had here. 
Plus, promised revisions have been abandoned an is now out of sync.

**Comment by d3fz** [comment]
Agreed. 

I've also tested this locally and apparently it's not finished as it is, tables stopped being generated after applying the suggested changes.

**Comment by lantis1008** [comment]
Hi @stopspazzing, do you think we could close this one please?

**Comment by stopspazzing** [comment]
Closing it as requested. It is a faster method and cleaner looking in code, but not end of world critical speeds. It will be a side project for me after the theme is finished.

**Comment by stopspazzing** [comment]
> Hi @stopspazzing, do you think we could close this one please?

Wow... so normal appending child's is faster it seems, just looks ugly and isn't proper way to do it. Weird.

https://jsbench.me/yokjapc2uk/1

**Pull request closed without merging**
