### PR TITLE
corrections in spanish language.

### PR DESCRIPTION
**Pull request by ftgalleg**

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I'm not entirely sure how you managed to send a pull request without your own copy of the repository, but on top of that I don't see any of the actual spanish updates you mention here, just a list of others contributions that are already in the repository.

You need to (1) fork the gargoyle project on github so you have a gargoyle project under your own account, (2) clone that repo, from your github account onto your computer, (3) make changes to that repo and commit them (4) push those changes to the repository in your github account and finally (5) send me a pull request.

If you're really having trouble figuring out github, I guess you can email me the new translation files -- I don't want to reject a contribution just because it isn't via github, even though that is my preferred method of accepting contributions.

However, this pull request doesn't seem to actually contain the new updates I think you wanted to submit, so I am closing it (at least for now).

**Comment by ftgalleg** [comment]
Hello,

i trying send you a push but, when i type the following command:

git push
and github login, i type my user and password, the github show's the
following error:

ericpaulbishop/gargoyle.git permission dennied to ftgalleg.
error 403 requesting the URL.
Fran.
El 24/02/2015 a las 0:15, Eric Bishop escribió:
> I'm not entirely sure how you managed to send a pull request without your own copy of the repository, but on top of that I don't see any of the actual spanish updates you mention here, just a list of others contributions that are already in the repository.
>
> You need to (1) fork the gargoyle project on github so you have a gargoyle project under your own account, (2) clone that repo, from your github account onto your computer, (3) make changes to that repo and commit them (4) push those changes to the repository in your github account and finally (5) send me a pull request.
>
> If you're really having trouble figuring out github, I guess you can email me the new translation files -- I don't want to reject a contribution just because it isn't via github, even though that is my preferred method of accepting contributions.
>
> However, this pull request doesn't seem to actually contain the new updates I think you wanted to submit, so I am closing it (at least for now).
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ericpaulbishop/gargoyle/pull/337#issuecomment-75659140

-- 
Necesitas liberar tu móvil? en 
http://www.oceanimei.es
podrás hacerlo con los mejores precios. Pruébanos y no te arrepentirás!.

**Comment by ericpaulbishop** [comment]
The problem is that you are trying to push to my repository, not your repository. You need to fork my project, then clone from git@github.com/ftgalleg/gargoyle.git, and then push to the same spot. It looks like you have not yet forked it to create your own copy -- do that first.

**Comment by ericpaulbishop** [comment]
Er, sorry, that should be git@github.com:ftgaleg/gargoyle.git (:, not / after github)

**Comment by ftgalleg** [comment]
Hello,

is the first time that i'm using a github.
  can you tell me step by step how to can collaborate/send you push/pull
request? i can't make it:(

Fran.
El 24/02/2015 a las 17:11, Eric Bishop escribió:
> Er, sorry, that should be git@github.com:ftgaleg/gargoyle.git (:, not / after github)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ericpaulbishop/gargoyle/pull/337#issuecomment-75786163

-- 
Necesitas liberar tu móvil? en 
http://www.oceanimei.es
podrás hacerlo con los mejores precios. Pruébanos y no te arrepentirás!.

**Comment by ifedorenko** [comment]
@ftgalleg "Pull Request" section of https://guides.github.com/activities/contributing-to-open-source/ has step-by-step instructions how to fork existing repository, make changes and open pull-requests.

**Comment by ftgalleg** [comment]
Hello,
 OK. i created a repository, i created a fork, clone and added the
changes and push it.
now, how to i can send you a pull request? in the wiki of github not
found instructions for this.

  My repository is:
https://github.com/ftgalleg/gargoyle

Fran.
Fran.
El 24/02/2015 a las 18:45, ifedorenko escribió:
> @ftgalleg "Pull Request" section of https://guides.github.com/activities/contributing-to-open-source/ has step-by-step instructions how to fork existing repository, make changes and open pull-requests.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ericpaulbishop/gargoyle/pull/337#issuecomment-75807083

-- 
Necesitas liberar tu móvil? en 
http://www.oceanimei.es
podrás hacerlo con los mejores precios. Pruébanos y no te arrepentirás!.

**Comment by ericpaulbishop** [comment]
Ok, I manually added your translation updates in commit d91212d.

I had to manually adjust only the files in the gargoyle/package/plugin-gargoyle-i18n-Spanish-ES, since it looks like you reverted a bunch of other files that have nothing to do with translation to an earlier version for some reason. Before making new commits please make sure you're up to date on the master branch.

**Pull request closed without merging**
